export const ROUTE_NAME = {
  DASHBOARD: 'Dashboard',
  COURSE: 'Course',
  ACCOUNT: 'Account',
  NEW_ACCOUNT: 'New Account',
  ACCOUNT_UPDATE: 'Account Update',
  PROFILE: 'Profile',
  PROPOSAL: 'Proposal',
  ROLL_UP: 'Roll up',
  NOTIFICATION: 'Notification',
  REPORT: 'Report',
  SETTING: 'Setting',
  GENERAL: 'General',
  POSITION: 'Position',
  NEW_POSITION: 'New Position',
  POSITION_UPDATE: 'Position Update',
  SHIFT: 'Shift',
  NEW_SHIFT: 'New Shift',
  SHIFT_UPDATE: 'Shift Update',
  BRANCH: 'Branch',
  NEW_BRANCH: 'New Branch',
  BRANCH_UPDATE: 'Branch Update',
  DEPARTMENT: 'Department',
  NEW_DEPARTMENT: 'New Department',
  DEPARTMENT_UPDATE: 'Department Update',
  HOLIDAY: 'Holiday',
  NEW_HOLIDAY: 'New Holiday',
  HOLIDAY_UPDATE: 'Holiday Update',
  HOLIDAY_SETTINGS_UPDATE: 'Holiday Settings Update',
  PERMISSION: 'Permission',
  PERMISSION_GROUP: 'PermissionGroup',
  ROLE: 'Role',
  AUTHORIZATION: 'Authorization',
};
