export const ROUTE_NAME = {
  DASHBOARD: "Dashboard",
  COURSE: "Course",
  ACCOUNT: "Account",
  PROFILE: "Profile",
  PROPOSAL: "Proposal",
  ROLL_UP: "Roll up",
  NOTIFICATION: "Notification",
  REPORT: "Report",
  SETTING: "Setting",
  GENERAL: "General",
  POSITION: "Position",
  SHIFT: "Shift",
  NEW_SHIFT: "New Shift",
  SHIFT_UPDATE: "Shift Update",
  BRANCH: "Branch",
  DEPARTMENT: "Department",
  HOLIDAY: "Holiday",
  NEW_HOLIDAY: "New Holiday",
  PERMISSION: "Permission",
  PERMISSION_GROUP: "PermissionGroup",
  ROLE: "Role",
  AUTHORIZATION: "Authorization",
};
