export const COLORS = {
  BUTTON_COLOR: '#3f51b5',
  TAB_INDICATOR: '#303c54',
  TAB_HOVER: '#303c54',
  DIALOG_TITLE_BACKGROUND: '#E7E7E7',
  SIDE_BAR_COLOR: '#3c4b64',
  FULLY_ROLL_CALL: '#caf7e3',
  FULLY_ABSENT_ROLL_CALL: '#fde2e2',
  FREE_DATE: '#eeeeee',
  SUCCESS: 'green',
  ERROR: 'red',
  WAITING: 'yellow',
  WHITE: 'white',
  REMOTE: '#fdffbc',
  OVERTIME: '#b1ffad',
  OVERTIME_REMOTE: '#ffd5cd',
};
