export const REDUX_STATE = {
  location: {
    SET_PROVINCES: 'SET_PROVINCES',
    SET_DISTRICTS: 'SET_DISTRICTS',
    SET_WARDS: 'SET_WARDS',
  },
  setting: {
    SET_GENERAL: 'SET_GENERAL',
  },

  shift: {
    EMPTY_VALUE: 'EMPTY_VALUE',
    GET_SHIFT: 'GET_SHIFT',
    SET_SHIFT: 'SET_SHIFT',
    GET_SHIFTS: 'GET_SHIFTS',
    DELETE_SHIFT: 'DELETE_SHIFT',
  },

  branch: {
    SET_BRANCHES: 'SET_BRANCHES',
    SET_BRANCH: 'SET_BRANCH',
    GET_BRANCH: 'GET_BRANCH',
    GET_BRANCHES: 'GET_BRANCHES',
    DELETE_BRANCH: 'DELETE_BRANCH',
  },

  department: {
    SET_DEPARTMENTS: 'SET_DEPARTMENTS',
    SET_DEPARTMENT: 'SET_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
    RESET_DEPARTMENT: 'RESET_DEPARTMENT'
  },

  position: {
    GET_POSITION: 'GET_POSITION',
    UPDATE_POSITION: 'UPDATE_NEW_POSITION',
    GET_POSITIONS: 'GET_POSITIONS',
    DELETE_POSITION: 'DELETE_POSITION',
  },
};
